<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_oxd_home_menu</name>
   <tag></tag>
   <elementGuidId>e5d286ce-a6c9-4856-a426-5120ed610522</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='top-ribbon-menu']/div/div/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.tooltipped.active > i.material-icons</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;oxd_home_menu&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>84cdc515-0c32-4bd6-a46f-54ca85d15cc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>material-icons</value>
      <webElementGuid>f22431fc-f20c-4d9f-aa51-31a42e11b030</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>oxd_home_menu</value>
      <webElementGuid>2a8de2ac-5e3a-418f-9c81-bfb4c344baef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top-ribbon-menu&quot;)/div[@class=&quot;top-ribbon-menu-basic-navigation menu-separator&quot;]/div[@class=&quot;basic-navigation&quot;]/a[@class=&quot;tooltipped active&quot;]/i[@class=&quot;material-icons&quot;]</value>
      <webElementGuid>7750682c-e622-4ce2-978d-fc6e2dce00ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='top-ribbon-menu']/div/div/a/i</value>
      <webElementGuid>2b39e816-c93b-4cce-9775-04a3e2176877</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout from all browsers'])[1]/following::i[1]</value>
      <webElementGuid>04e1a67c-7e47-40be-a42c-5fb3108e95c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='arrow_drop_down'])[1]/following::i[1]</value>
      <webElementGuid>e3e39a1d-2987-4da8-9eac-68e8809ec27c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employee List'])[1]/preceding::i[1]</value>
      <webElementGuid>c8bf8120-e094-40d3-a636-9827d7802baf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Directory'])[1]/preceding::i[1]</value>
      <webElementGuid>0351ffcc-aea3-46ea-9c23-78f18220f9fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='oxd_home_menu']/parent::*</value>
      <webElementGuid>3156dccf-ba30-48aa-8098-abf1895d4a16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//top-menu/div/div/div/div/a/i</value>
      <webElementGuid>d717af55-d94c-4601-837c-d0a19c95bc8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[(text() = 'oxd_home_menu' or . = 'oxd_home_menu')]</value>
      <webElementGuid>8b593c4c-d35c-40cf-aaa0-ea1b513afdeb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
