<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_</name>
   <tag></tag>
   <elementGuidId>c4af2049-2a82-4ea1-8e96-44b7fcf61b1d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a:nth-of-type(3)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='SIvCob']/a[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;తెలుగు&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>22d56639-435d-438e-be73-03b8267a92df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.google.com/setprefs?sig=0_vJRIxPgGysL_yJ8ONJejMdZWVsQ%3D&amp;hl=te&amp;source=homepage&amp;sa=X&amp;ved=0ahUKEwiTq5rErvOLAxUVTmwGHYLCD2IQ2ZgBCBo</value>
      <webElementGuid>0021bef7-2912-47d0-b044-3694689444f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>తెలుగు</value>
      <webElementGuid>e2072767-dfde-42c3-9956-64767eca0ed6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SIvCob&quot;)/a[3]</value>
      <webElementGuid>39bf793b-21cf-4cd9-b469-845993062674</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SIvCob']/a[3]</value>
      <webElementGuid>af264bd3-9dda-4647-8fd2-cb75aab47e52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'తెలుగు')]</value>
      <webElementGuid>248039f4-8713-4dfb-b3af-529357418a66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='বাংলা'])[1]/following::a[1]</value>
      <webElementGuid>cf304b08-b376-4335-899a-6e14887a6406</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='हिन्दी'])[1]/following::a[2]</value>
      <webElementGuid>a87bd3f3-8b83-4a40-a2a7-4659d4c9e910</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='मराठी'])[1]/preceding::a[1]</value>
      <webElementGuid>cfcb7ad0-bd6d-4059-8776-b2c3804ce90f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='தமிழ்'])[1]/preceding::a[2]</value>
      <webElementGuid>2aa6e5a3-6e1d-4482-8bbb-d3fbc233e1bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='తెలుగు']/parent::*</value>
      <webElementGuid>4485a1f6-af58-49e7-8f12-f91499a5a7e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.google.com/setprefs?sig=0_vJRIxPgGysL_yJ8ONJejMdZWVsQ%3D&amp;hl=te&amp;source=homepage&amp;sa=X&amp;ved=0ahUKEwiTq5rErvOLAxUVTmwGHYLCD2IQ2ZgBCBo')]</value>
      <webElementGuid>1af04d01-1d24-4936-b77e-758d4be11c98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]</value>
      <webElementGuid>ee291de6-551b-42f9-90a6-7b451f48d033</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.google.com/setprefs?sig=0_vJRIxPgGysL_yJ8ONJejMdZWVsQ%3D&amp;hl=te&amp;source=homepage&amp;sa=X&amp;ved=0ahUKEwiTq5rErvOLAxUVTmwGHYLCD2IQ2ZgBCBo' and (text() = 'తెలుగు' or . = 'తెలుగు')]</value>
      <webElementGuid>91ac02b7-451f-4863-a616-fa5e887a0be4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SIvCob']/a</value>
      <webElementGuid>208a9bbd-44d5-4af6-9562-33cdb9cab307</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'हिन्दी')]</value>
      <webElementGuid>05d0f4eb-a5a0-4f1e-aabc-1c66e19bdbb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Report inappropriate predictions'])[1]/following::a[1]</value>
      <webElementGuid>01d4780b-6f6c-4baf-9f85-73622c529d3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='বাংলা'])[1]/preceding::a[1]</value>
      <webElementGuid>e6e02ee8-6a5d-4457-b8e6-75cfa404c2c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='తెలుగు'])[1]/preceding::a[2]</value>
      <webElementGuid>a5072237-6a38-4f4b-93ab-15e662db3637</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='हिन्दी']/parent::*</value>
      <webElementGuid>4caf0a30-5c8d-4136-952b-939def6a2458</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.google.com/setprefs?sig=0_6CJIFytWj55THYnVil-bUPX4mY8%3D&amp;hl=hi&amp;source=homepage&amp;sa=X&amp;ved=0ahUKEwiNqqGLrfOLAxWdUPUHHXufNQ4Q2ZgBCBg')]</value>
      <webElementGuid>bfa64022-e07a-453f-8fc2-a643755e4de2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/a</value>
      <webElementGuid>c37efa18-c1fe-4d76-b9c3-81aa360cff39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.google.com/setprefs?sig=0_6CJIFytWj55THYnVil-bUPX4mY8%3D&amp;hl=hi&amp;source=homepage&amp;sa=X&amp;ved=0ahUKEwiNqqGLrfOLAxWdUPUHHXufNQ4Q2ZgBCBg' and (text() = 'हिन्दी' or . = 'हिन्दी')]</value>
      <webElementGuid>508d537e-fd24-4404-8f51-ab5c1599b2d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
