<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__1_2_3</name>
   <tag></tag>
   <elementGuidId>4f17e8f9-8278-4fe5-a334-4a4ff19fca39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a:nth-of-type(7)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='SIvCob']/a[7]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;ಕನ್ನಡ&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2ac3ce34-ce50-48be-8d37-c3f21fcb6fd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.google.com/setprefs?sig=0_vJRIxPgGysL_yJ8ONJejMdZWVsQ%3D&amp;hl=kn&amp;source=homepage&amp;sa=X&amp;ved=0ahUKEwiTq5rErvOLAxUVTmwGHYLCD2IQ2ZgBCB4</value>
      <webElementGuid>08e6dfaa-da4a-434c-b757-36cae792c9c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ಕನ್ನಡ</value>
      <webElementGuid>f20ccdb1-03b9-4e3d-b72e-dc18fe41d28c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SIvCob&quot;)/a[7]</value>
      <webElementGuid>ac86978d-7760-4645-9941-2c6899aeaa65</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SIvCob']/a[7]</value>
      <webElementGuid>b61b8375-375a-4d95-a96d-0c78b45f495c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'ಕನ್ನಡ')]</value>
      <webElementGuid>283628b6-c9a6-4a50-bc8e-4fe34f029b56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ગુજરાતી'])[1]/following::a[1]</value>
      <webElementGuid>cfe627b7-87da-421a-9823-659b9b979003</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='தமிழ்'])[1]/following::a[2]</value>
      <webElementGuid>5d6d1667-1579-429e-aa81-058cd7ff4fdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='മലയാളം'])[1]/preceding::a[1]</value>
      <webElementGuid>f83f4481-be7c-4e33-a827-d9b22efb4758</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ਪੰਜਾਬੀ'])[1]/preceding::a[2]</value>
      <webElementGuid>392d1a19-0b06-48fa-96f7-ae21ebb4aeaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ಕನ್ನಡ']/parent::*</value>
      <webElementGuid>99bbfd7b-11fa-4e68-a2c2-ab08064b749e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.google.com/setprefs?sig=0_vJRIxPgGysL_yJ8ONJejMdZWVsQ%3D&amp;hl=kn&amp;source=homepage&amp;sa=X&amp;ved=0ahUKEwiTq5rErvOLAxUVTmwGHYLCD2IQ2ZgBCB4')]</value>
      <webElementGuid>43888bf9-3cc2-4975-aabc-6f4868acc380</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[7]</value>
      <webElementGuid>95286916-bcf0-4c4e-9ce8-523e66b0eac3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.google.com/setprefs?sig=0_vJRIxPgGysL_yJ8ONJejMdZWVsQ%3D&amp;hl=kn&amp;source=homepage&amp;sa=X&amp;ved=0ahUKEwiTq5rErvOLAxUVTmwGHYLCD2IQ2ZgBCB4' and (text() = 'ಕನ್ನಡ' or . = 'ಕನ್ನಡ')]</value>
      <webElementGuid>8514da63-ab6d-404b-ab15-936359e3408e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
