<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Retry Login</name>
   <tag></tag>
   <elementGuidId>b702b32d-1e7b-446c-9ac8-2605a02dd885</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='divContent']/div[2]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.dashboardCard-title-for-card</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Retry Login&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1057c619-3224-44b9-8eea-271702ce95fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dashboardCard-title-for-card</value>
      <webElementGuid>df87c659-e4bb-4a68-bfc1-ad95d240193f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Retry Login</value>
      <webElementGuid>4bb0b73c-5c77-4301-9529-338c7267d39e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divContent&quot;)/div[@class=&quot;box login-container&quot;]/div[@class=&quot;orangehrm-form&quot;]/div[@class=&quot;dashboardCard-title-for-card&quot;]</value>
      <webElementGuid>2efe7da1-3ca3-46e5-b94a-b5c87f9e8e40</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divContent']/div[2]/div/div</value>
      <webElementGuid>8956c204-541b-4622-8aac-88a89694cb68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/preceding::div[1]</value>
      <webElementGuid>073893d9-1443-4fd6-b541-c0ef053ba7aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Retry Login']/parent::*</value>
      <webElementGuid>1196d2d7-4d43-45ee-83db-4bafdead498e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div</value>
      <webElementGuid>d1311677-fd4e-476c-b134-24a1390036eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Retry Login' or . = 'Retry Login')]</value>
      <webElementGuid>9555c75a-4d73-48c7-af0c-f47cb42383bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
